export type XdicDailyExpression = {
  id: string;
  en: string;
  ko: string;
  source: 'Travel' | 'Business';
  tag: string;
  href: '/travel' | '/business';
};

// 기존 X-DIC Travel / Business 허브에 이미 노출 중인 표현만 재사용합니다.
// 새 AI 문장을 생성하지 않으며, 이 파일만 편집하면 '오늘의 표현' 풀을 관리할 수 있습니다.
export const XDIC_DAILY_EXPRESSIONS: XdicDailyExpression[] = [
  {
    id: "travel-check-in-counter",
    en: "Where is the check-in counter?",
    ko: "체크인 카운터가 어디에 있나요?",
    source: "Travel",
    tag: "공항",
    href: "/travel",
  },
  {
    id: "travel-aisle-seat",
    en: "Could I have an aisle seat?",
    ko: "통로 쪽 좌석으로 받을 수 있을까요?",
    source: "Travel",
    tag: "공항",
    href: "/travel",
  },
  {
    id: "travel-transfer",
    en: "Where do I transfer?",
    ko: "어디에서 갈아타나요?",
    source: "Travel",
    tag: "교통",
    href: "/travel",
  },
  {
    id: "travel-reservation-kim",
    en: "I have a reservation under Kim.",
    ko: "김이라는 이름으로 예약했습니다.",
    source: "Travel",
    tag: "호텔",
    href: "/travel",
  },
  {
    id: "travel-checkout",
    en: "What time is check-out?",
    ko: "체크아웃은 몇 시인가요?",
    source: "Travel",
    tag: "호텔",
    href: "/travel",
  },
  {
    id: "travel-towel",
    en: "Could I get another towel?",
    ko: "수건을 하나 더 받을 수 있을까요?",
    source: "Travel",
    tag: "호텔",
    href: "/travel",
  },
  {
    id: "travel-table-two",
    en: "A table for two, please.",
    ko: "두 명 자리 부탁합니다.",
    source: "Travel",
    tag: "식당",
    href: "/travel",
  },
  {
    id: "travel-like-this",
    en: "I'd like this, please.",
    ko: "이걸로 주세요.",
    source: "Travel",
    tag: "식당·쇼핑",
    href: "/travel",
  },
  {
    id: "travel-bill",
    en: "Could we have the bill, please?",
    ko: "계산서 부탁합니다.",
    source: "Travel",
    tag: "식당",
    href: "/travel",
  },
  {
    id: "travel-how-much",
    en: "How much is this?",
    ko: "이것은 얼마인가요?",
    source: "Travel",
    tag: "쇼핑",
    href: "/travel",
  },
  {
    id: "travel-exchange",
    en: "I'd like to exchange this for something else.",
    ko: "다른 제품으로 교환하고 싶습니다.",
    source: "Travel",
    tag: "쇼핑",
    href: "/travel",
  },
  {
    id: "travel-card",
    en: "Can I pay by card?",
    ko: "카드로 결제할 수 있나요?",
    source: "Travel",
    tag: "결제",
    href: "/travel",
  },
  {
    id: "travel-station",
    en: "How can I get to the station?",
    ko: "역에 어떻게 가나요?",
    source: "Travel",
    tag: "길찾기",
    href: "/travel",
  },
  {
    id: "travel-how-long",
    en: "How long does it take?",
    ko: "얼마나 걸리나요?",
    source: "Travel",
    tag: "길찾기",
    href: "/travel",
  },
  {
    id: "travel-wallet",
    en: "I lost my wallet.",
    ko: "지갑을 잃어버렸어요.",
    source: "Travel",
    tag: "도움",
    href: "/travel",
  },
  {
    id: "business-attached-file",
    en: "Please find the attached file.",
    ko: "첨부 파일을 확인해 주세요.",
    source: "Business",
    tag: "이메일",
    href: "/business",
  },
  {
    id: "business-updated-version",
    en: "Could you send me the updated version?",
    ko: "업데이트된 버전을 보내주시겠어요?",
    source: "Business",
    tag: "이메일",
    href: "/business",
  },
  {
    id: "business-reply",
    en: "I look forward to your reply.",
    ko: "회신을 기다리겠습니다.",
    source: "Business",
    tag: "이메일",
    href: "/business",
  },
  {
    id: "business-next-item",
    en: "Let's move on to the next item.",
    ko: "다음 안건으로 넘어가겠습니다.",
    source: "Business",
    tag: "회의",
    href: "/business",
  },
  {
    id: "business-agree-point",
    en: "I agree with your point.",
    ko: "말씀하신 점에 동의합니다.",
    source: "Business",
    tag: "회의",
    href: "/business",
  },
  {
    id: "business-clarify",
    en: "Could you clarify what you mean?",
    ko: "무슨 뜻인지 좀 더 설명해 주시겠어요?",
    source: "Business",
    tag: "회의",
    href: "/business",
  },
  {
    id: "business-message",
    en: "Could I leave a message?",
    ko: "메시지를 남겨도 될까요?",
    source: "Business",
    tag: "전화",
    href: "/business",
  },
  {
    id: "business-call-back",
    en: "I'll call you back later.",
    ko: "나중에 다시 전화드리겠습니다.",
    source: "Business",
    tag: "전화",
    href: "/business",
  },
  {
    id: "business-available",
    en: "Are you available tomorrow afternoon?",
    ko: "내일 오후에 시간 괜찮으세요?",
    source: "Business",
    tag: "일정",
    href: "/business",
  },
  {
    id: "business-reschedule",
    en: "Could we reschedule the meeting?",
    ko: "회의 일정을 다시 잡을 수 있을까요?",
    source: "Business",
    tag: "일정",
    href: "/business",
  },
  {
    id: "business-deadline",
    en: "The deadline is Friday.",
    ko: "마감일은 금요일입니다.",
    source: "Business",
    tag: "일정",
    href: "/business",
  },
  {
    id: "business-review-tomorrow",
    en: "Could you review this by tomorrow?",
    ko: "내일까지 이것을 검토해 주시겠어요?",
    source: "Business",
    tag: "요청·보고",
    href: "/business",
  },
  {
    id: "business-on-schedule",
    en: "The project is on schedule.",
    ko: "프로젝트는 일정대로 진행되고 있습니다.",
    source: "Business",
    tag: "요청·보고",
    href: "/business",
  },
  {
    id: "business-problem",
    en: "We have encountered a problem.",
    ko: "문제가 발생했습니다.",
    source: "Business",
    tag: "요청·보고",
    href: "/business",
  },
  {
    id: "business-discuss-terms",
    en: "We would like to discuss the terms.",
    ko: "조건을 협의하고 싶습니다.",
    source: "Business",
    tag: "협상·계약",
    href: "/business",
  },
  {
    id: "business-agreement",
    en: "We have reached an agreement.",
    ko: "합의에 도달했습니다.",
    source: "Business",
    tag: "협상·계약",
    href: "/business",
  },
];
